apiVersion: apps/v1
kind: Deployment
metadata:
  name: eth-app-deployment
  namespace: eth-app-namespace  
spec:
  replicas: 1 # we need one instance of the application
  selector:
    matchLabels:
      component: eth-app # in case we want to connect to other service (networking cluster IP  )
  template:
    metadata:
      labels:
        component: eth-app
    spec:
      containers:
        - name: eth-app
          image: abdm6464/eth-app-notification:v0.0.2 #  this my own  image for the application in the docker hub support rinkeby network ; you can build your own image and push it to private registry see the readme please 
          env:
            - name: ACCOUNT
              value:  #add the Ethereum address of your account
            - name: AMOUNT
              value: '5'  #add the minimum amount of ether 
            - name: TIME
              value: '09:13' #add the time when you want to  get the daily notification the  format should be hh:mm at UTC Time ZONE
            - name: INFURA_ID #   all secret data should store in secret we don't want to expose our keys to the public  see the readme please 
              valueFrom: 
                secretKeyRef: 
                  name: eth-app-tokens # the secret that  store all our keys
                  key: INFURA_ID # the key stored in the secret to get the INFURA_ID
            - name: TELEGRAM_TOKEN #   secret key
              valueFrom: 
                secretKeyRef: 
                  name: eth-app-tokens # the secret that  store all our keys
                  key: TELEGRAM_TOKEN # the key stored in the secret to get the TELEGRAM_TOKEN
            - name: TELEGRAM_CHAT_ID 
              value:  # add your telegram channel_id should be a number
            - name: SLACK_TOKEN # secret key
              valueFrom: 
                secretKeyRef: 
                  name: eth-app-tokens  # the secret when we store all our keys 
                  key: SLACK_TOKEN  # the key stored in the secret to get the TELEGRAM_TOKEN
            - name: SLACK_CHAT_ID 
              value:  # add your slack chat id   to send you a notification  

              # Please notice in order o get the application work you need to fill env var 
         