apiVersion: apps/v1
kind: Deployment
metadata:
  name: eth-app-deployment
  namespace: eth-app-namespace  
spec:
  replicas: 1
  selector:
    matchLabels:
      component: eth-app
  template:
    metadata:
      labels:
        component: eth-app
    spec:
      containers:
        - name: eth-app
          image: abdm6464/eth-app-notification:v0.0.1 # or you can use private registry
          env:
            - name: ACCOUNT
              value:  #add the Ethereum addresses of your account
            - name: AMOUNT
              value: '5'  #add the minimum amout of ether 
            - name: TIME
              value: '09:13' #add the time when you want the  script execut every day forma should be 24 
            - name: INFURA_ID #  secret key
              valueFrom: 
                secretKeyRef: 
                  name: eth-app-tokens
                  key: INFURA_ID
            - name: TELEGRAM_TOKEN #  
              valueFrom: 
                secretKeyRef: 
                  name: eth-app-tokens
                  key: TELEGRAM_TOKEN 
            - name: TELEGRAM_CHAT_ID 
              value:  # add your telegram channel_id should be a number
            - name: SLACK_TOKEN # secret key
              valueFrom: 
                secretKeyRef: 
                  name: eth-app-tokens 
                  key: SLACK_TOKEN 
            - name: SLACK_CHAT_ID 
              value: azae # add your telegram token to send you a notification  
         