apiVersion: v1
kind: Secret
metadata:
  name: eth-app-tokens
type: Opaque
stringData:
  INFURA_ID: b34ec3bc8dd346eb94f3337e1c9f7cb6 #add your infura token
  SLACK_TOKEN: xoxb-1405736513255-1426642695060-uKzAJIZqaccil2bX0phaeJdr # add your Slack Token
  TELEGRAM_TOKEN: 1245097298:AAHRaPbq7AY3YVb7-f04nIjWbYnCprjrI6s # add your telegram token